name: Fetch Commit Details

on:
  push:
    branches:
      - main  # Change this to your working branch

jobs:
  fetch_commit_details:
    runs-on: windows-latest  # Using Windows since it's a .NET Framework project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Fetch at least 2 commits to compare changes

      - name: Set up PowerShell
        run: pwsh --version  # Verify PowerShell is installed

      - name: Fetch Commit Details
        run: pwsh ./scripts/fetch_commit.ps1
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # Use GitHub token for API requests

      - name: Upload Commit Details
        uses: actions/upload-artifact@v4
        with:
      - name: commit-details
        path: ./commit-details.json
 
      - name: Print Commit Details
        run: cat commit-details.json
