name: Fetch Commit Details

on:
  push:
    branches:
      - main  # Change this to your working branch

jobs:
  fetch_commit_details:
    runs-on: windows-latest  # Using Windows since it's a .NET Framework project

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ✅ Ensures GitHub fetches all commits (prevents caching issues)

      - name: Set up PowerShell
        run: pwsh --version  # ✅ Verify PowerShell is installed

      - name: Fetch Commit Details
        run: pwsh -ExecutionPolicy Bypass -File ./scripts/fetch_commit.ps1
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # ✅ Use GitHub token for API requests

      - name: Debug - List Files
        run: ls -R  # ✅ Check all files before printing commit details

      - name: Upload Commit Details
        uses: actions/upload-artifact@v4
        with:
          name: commit-details
          path: artifacts/commit-details.json  # ✅ Added commit changes to the file

      - name: Print Commit Details
        run: cat artifacts/commit-details.json  # ✅ Print commit changes
        
      - name: Commit & Push Updated JSON to GitHub    # ✅ Using github bot to update commit-details.json file
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add artifacts/commit-details.json
          git commit -m "🤖 Update commit-details.json after workflow run"
          git push origin main
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}  # ✅ GitHub token to authenticate push
